project:
  type: book
  output-dir: docs

book:
  title: "Phd scripts book"
  author: "G. Bediaga"
  date: last-modified
  chapters: 
    - index.qmd
    - part: 10_data_prep.qmd
      chapters: 
        - 11_pps_prep.qmd
  appendices:
    - 99_references.qmd
    
    #     - 12_if100_prep.qmd
    # - part: 20_data_exp.qmd
    #   chapters: 
    #     - 21_wd_exp.qmd
    # - part: 30_data_analisys.qmd
    #   chapters: 
    #     - 31_tree_height_from_lidar.qmd
    #     - 32_tree_height_from_lidar_all_apus.qmd
    #     - 33_estimate_biomass.qmd
    #     - 34_gustavo_with_Lidar_H.qmd

bibliography: mendeley.bib

format:
  html:
    theme: cosmo
    toc: true
    toc-depth: 2
    css: styles.css
    code-line-numbers: true
    code-fold: true
    
  # pdf:
  #   documentclass: scrreprt

editor: visual

